export const makams = [
  {
    name: 'Rast',
    slug: 'rast',
    label: 'Temel Makamlar',
    journey: {
      begin: { root1: 'Rast', pow1: 'Rast' },
      middle: {
        root1: 'Neva',
        pow1: 'Rast',
        root2: 'Neva',
        pow2: 'Buselik',
        root3: 'Segah',
        pow3: 'Segah',
      },
      end: { root1: 'Rast', pow1: 'Rast' },
    },
    desc: 'Musiki teori tarihi boyunca tüm teori kitaplarında ana makamlar kategorisinde değerlendirilen Rast makamı birçok ekolde temel makam olarak kabul edilmiştir. Makamın başlangıç noktası Rast perdesi üzerindeki Rast çeşnisidir. Daha sonra eksenini Neva bölgesine taşır. Bu eksende Rast ve Buselik çeşnileri gösterir. Ardından Segâh ekseninde Segâh çeşnisini gösterip Rast üzerinde Rast çeşniyle karar vererek başladığı noktaya geri döner. Makamın olası geçki ve genişlemeleri için bkz. Çeşni Evreni.',
  },
  {
    name: 'Buselik',
    slug: 'buselik',
    label: 'Temel Makamlar',
    journey: {
      begin: { root1: 'Hüseyni', pow1: 'Perde' },
      middle: {
        root1: 'Dügah',
        pow1: 'Buselik',
        root2: 'Rast',
        pow2: 'Nigar',
        root3: 'Hüseyni',
        pow3: 'Kürdi',
      },
      end: { root1: 'Dügah', pow1: 'Buselik' },
    },
    desc: 'Tüm teori kitaplarında temel makam olarak gösterilen Buselik makamının başlangıç noktası Hüseyni perdesidir. Daha sonra Dügah üzerindeki Buselik çeşnisini gösterir ve ardından Rast perdesindeki Nigar çeşnisini gösterip Hüseyni perdesi üzerindeki Kürdi çeşniyle seyrine devam eder. Dügah perdesinde Buselik çeşnisiyle birlikte karar eder. Makamın olası geçki ve genişlemeleri için bkz. Çeşni Evreni.',
  },
  {
    name: 'Uşşak',
    slug: 'uşşak',
    label: 'Temel Makamlar',
    journey: {
      begin: { root1: 'Dügah', pow1: 'Uşşak' },
      middle: {
        root1: 'Neva',
        pow1: 'Buselik',
        root2: 'Segah',
        pow2: 'Segah',
      },
      end: { root1: 'Dügah', pow1: 'Uşşak' },
    },
    desc: 'Uşşak makamı Dügah üzerinden Uşşak çeşniyle başlar. Daha sonra Neva perdesi üzerinde Buselik çeşnisini gösterir. Ardından seyrine Segah perdesinde Segah çeşnisini göstererek devam eder. Dügah perdesindeki Uşşak çeşnisiyle karar eder. Makamın olası geçki ve genişlemeleri için bkz. Çeşni Evreni.',
  },
  {
    name: 'Kürdi',
    slug: 'kürdi',
    label: 'Temel Makamlar',
    journey: {
      begin: { root1: 'Dügah', pow1: 'Kürdi' },
      middle: {
        root1: 'Neva',
        pow1: 'Buselik',
        root2: 'Çargah',
        pow2: 'Nigar',
      },
      end: { root1: 'Dügah', pow1: 'Kürdi' },
    },
    desc: 'Kürdi makamının başlangıç noktası Dügah perdesidir. Burada Dügah perdesinde Kürdi çeşnisi gösterip Neva perdesi üzerindeki Buselik çeşnisine geçer. Ardından Çargah perdesinde Nigar çeşnisi göstererek seyrine devam eder. Dügah perdesi üzerinde Kürdi çeşnisiyle başladığı şekliyle karar verir. Makamın olası geçki ve genişlemeleri için bkz. Çeşni Evreni.',
  },
  {
    name: 'Hüseyni',
    slug: 'hüseyni',
    label: 'Temel Makamlar',
    journey: {
      begin: { root1: 'Hüseyni', pow1: 'Perde' },
      middle: {
        root1: 'Hüseyni',
        pow1: 'Uşşak',
        root2: 'Çargah',
        pow2: 'Nigar',
      },
      end: { root1: 'Dügah', pow1: 'Hüseyni' },
    },
    desc: 'Makama adını veren Hüseyni perdesi bu makamın başlangıç noktasıdır. Buradan Hüseyni perdesi üzerinde Uşşak çeşnisine geçer. Çargah üzerinden Nigar çeşnisinde kalışlar yaparak Dügah perdesi üzerinde Hüseyni çeşnisiyle karar eder. Makamın olası geçki ve genişlemeleri için bkz. Çeşni Evreni.',
  },
  {
    name: 'Bayati',
    slug: 'bayati',
    label: 'Temel Makamlar',
    journey: {
      begin: { root1: 'Neva', pow1: 'Buselik' },
      middle: {
        root1: 'Dügah',
        pow1: 'Uşşak',
        root2: 'Neva',
        pow2: 'Hicaz',
      },
      end: { root1: 'Dügah', pow1: 'Uşşak' },
    },
    desc: 'Neva perdesi makamın başlangıç noktasıdır. Neva üzerindeki Buselik çeşnisini gösterdikten sonra Dügah perdesinde Uşşak çeşnisine geçiş yapar. Daha sonra Neva perdesinde Hicaz çeşnisi yapıp yine Dügah perdesindeki Uşşak çeşnisiyle seyrini sonlandırır. Makamın olası geçki ve genişlemeleri için bkz. Çeşni Evreni.',
  },
  {
    name: 'Hüzzam',
    slug: 'hüzzam',
    label: 'Temel Makamlar',
    journey: {
      begin: { root1: 'Segah', pow1: 'Hüzzam' },
      middle: {
        root1: 'Neva',
        pow1: 'Hicaz',
        root2: 'Gerdaniye',
        pow2: 'Buselik',
      },
      end: { root1: 'Segah', pow1: 'Segah' },
    },
    desc: 'Hüzzam makamı Segah perdesi üzerinde Hüzzam çeşnisiyle başlar. Önce Neva üzerinde Hicaz çeşniyle sonra Gerdaniye perdesinde Buselik çesnisini gösterir. Segah üzerinde Segah çeşnisiyle karar eder.  Makamın olası geçki ve genişlemeleri için bkz. Çeşni Evreni.',
  },
  {
    name: 'Hicaz',
    slug: 'hicaz',
    label: 'Temel Makamlar',
    journey: {
      begin: { root1: 'Dügah', pow1: 'Hicaz' },
      middle: {
        root1: 'Neva',
        pow1: 'Rast',
        root2: 'Neva',
        pow2: 'Buselik',
      },
      end: { root1: 'Dügah', pow1: 'Hicaz' },
    },
    desc: 'Makamın başlangıç noktası Dügah perdesindeki Hicaz çeşnisidir. Önce Neva üzerindeki Rast çeşnisini gösterip sonra Neva perdesindeki Buselik çeşnisiyle seyrine devam eder. Dügah üzerindeki Hicaz çeşnisiyle başladığı noktaya geri döner. Makamın olası geçki ve genişlemeleri için bkz. Çeşni Evreni.',
  },
  {
    name: 'Hicaz Hümayun',
    slug: 'hicaz hümayun',
    label: 'Temel Makamlar',
    journey: {
      begin: { root1: 'Neva', pow1: 'Buselik' },
      middle: {
        root1: 'Dügah',
        pow1: 'Hicaz',
        root2: 'Buselik',
        pow2: 'Nişabur',
      },
      end: { root1: 'Dügah', pow1: 'Hicaz' },
    },
    desc: 'Neva perdesi üzerindeki Buselik çeşnisi makamın başlangıç noktasıdır. Buradan Dügah perdesindeki Hicaz çeşnisine geçer. Daha sonra Buselik perdesi üzerinde Nişabur çeşnisi yapıp tekrar Dügah perdesindeki Hicaz çeşnisine geri döner ve bu karar verir. Makamın olası geçki ve genişlemeleri için bkz. Çeşni Evreni.',
  },
  {
    name: 'Uzzal',
    slug: 'uzzal',
    label: 'Temel Makamlar',
    journey: {
      begin: { root1: 'Hüseyni', pow1: 'Uşşak' },
      middle: {
        root1: 'Dügah',
        pow1: 'Uzzal',
        root2: 'Hüseyni',
        pow2: 'Kürdi',
      },
      end: { root1: 'Dügah', pow1: 'Uzzal' },
    },
    desc: 'Uzzal makamı Hüseyni perdesi üzerindeki Uşşak çeşnisi üzerinden başlar ve ardından Dügah perdesi üzerindeki Uzzal çeşnisine geçiş yapar. Daha sonra Hüseyni perdesi üzerindeki Kürdi çeşniyle seyrine devam eder. Dügah üzerinde Uzzal çeşnisiyle karar noktasına gelir. Makamın olası geçki ve genişlemeleri için bkz. Çeşni Evreni.',
  },
  {
    name: 'Zirgüle',
    slug: 'zirgüle',
    label: 'Temel Makamlar',
    journey: {
      begin: { root1: 'Dügah', pow1: 'Uzzal' },
      middle: {
        root1: 'Hüseyni',
        pow1: 'Hicaz',
      },
      end: { root1: 'Dügah', pow1: 'Uzzal' },
    },
    desc: 'Zirgüle makamı Dügah üzerindeki Uzzal çeşnisiyle başlagıcını yapar ve ardından Hüseyni perdesindeki Hicaz çeşnisiyle seyrine devam eder. Dügah perdesi üzerindeki Uzzal çeşnisiyle başladığı şekliyle karar eder. Makamın olası geçki ve genişlemeleri için bkz. Çeşni Evreni.',
  },
  {
    name: 'Neva',
    slug: 'neva',
    label: 'Temel Makamlar',
    journey: {
      begin: { root1: 'Neva', pow1: 'Perde' },
      middle: {
        root1: 'Dügah',
        pow1: 'Uşşak',
        root2: 'Neva',
        pow2: 'Rast',
        root3: 'Eviç',
        pow3: 'Segah',
      },
      end: { root1: 'Dügah', pow1: 'Uşşak' },
    },
    desc: 'Neva makamının başlangıç noktası makama ismini veren perde olan Neva perdesidir. Buradan Dügah perdesindeki Uşşak çeşnisine geçer. Daha sonra Neva üzerinde Rast çeşni ve Eviç üzerinde Segah çeşnisi göstererek seyrine devam eder. Ardından Dügah üzerindeki Uşşak çeşnisiyle karar verir. Makamın olası geçki ve genişlemeleri için bkz. Çeşni Evreni.',
  },
  {
    name: 'Suzinak (Zirgülesiz)',
    slug: 'suzinak (zirgülesiz)',
    label: 'Temel Makamlar',
    journey: {
      begin: { root1: 'Neva', pow1: 'Hicaz' },
      middle: {
        root1: 'Rast',
        pow1: 'Rast',
        root2: 'Segah',
        pow2: 'Segah',
      },
      end: { root1: 'Rast', pow1: 'Rast' },
    },
    desc: 'Makamın başlangıç noktasını Neva perdesindeki Hicaz çeşnisi oluşturur. Daha sonra Rast üzerinde Rast çeşnine geçer. Ardından Segah perdesindeki Segah çeşnine gösterip terkar Rast perdesindeki Rast çeşnisine geçerek burada karar verir. Makamın olası geçki ve genişlemeleri için bkz. Çeşni Evreni.',
  },
  {
    name: 'Suzinak (Zirgüleli)',
    slug: 'suzinak (zirgüleli)',
    label: 'Temel Makamlar',
    journey: {
      begin: { root1: 'Neva', pow1: 'Hicaz' },
      middle: {
        root1: 'Rast',
        pow1: 'Hicaz',
        root2: 'Segah',
        pow2: 'Segah',
      },
      end: { root1: 'Rast', pow1: 'Hicaz' },
    },
    desc: 'Neva perdesindeki Hicaz çeşnisi makamın başlangıç noktasını oluşturur. Daha sonra bu makamı Zirgüleli Suzinak makamından ayıran çeşni olan Rast üzerinde Hicaz çeşnine geçer. Ardından Segah perdesindeki Segah çeşnine gösterip tekrar Rast perdesindeki Hicaz çeşnisini gösterip karar verir. Makamın olası geçki ve genişlemeleri için bkz. Çeşni Evreni.',
  },
  {
    name: 'Karcığar',
    slug: 'karcığar',
    label: 'Temel Makamlar',
    journey: {
      begin: { root1: 'Neva', pow1: 'Hicaz' },
      middle: {
        root1: 'Dügah',
        pow1: 'Uşşak',
        root2: 'Çargah',
        pow2: 'Nikriz',
      },
      end: { root1: 'Dügah', pow1: 'Uşşak' },
    },
    desc: 'Neva perdesi üzerindeki Hicaz çeşnisinden başlar. Buradan Dügah üzerindeki Uşşak çeşnisine geçer. Çargah üzerindeki Nikriz çeşnisini gösterdikten sonra tekrar Dügah üzerindeki Uşşak çeşnisine döner ve burada karar verir. Makamın olası geçki ve genişlemeleri için bkz. Çeşni Evreni.',
  },
  {
    name: 'Huzi',
    slug: 'huzi',
    label: 'Temel Makamlar',
    journey: {
      begin: { root1: 'Dügah', pow1: 'Uşşak' },
      middle: {
        root1: 'Neva',
        pow1: 'Buselik',
        root2: 'Rast',
        pow2: 'Rast',
      },
      end: { root1: 'Dügah', pow1: 'Uşşak' },
    },
    desc: 'Dügah üzerindeki Uşşak çeşnisiyle başlayıp Neva perdesindeki Buselik çeşnisine geçer. Daha sonra Rast perdesinde Rast çeşnisini gösterip Dügah perdesinde Uşşak çeşnisiyle karar verir. Makamın olası geçki ve genişlemeleri için bkz. Çeşni Evreni.',
  },
  {
    name: 'Segah',
    slug: 'segah',
    label: 'Mürekkeb Makamlar',
    journey: {
      begin: { root1: 'Segah', pow1: 'Segah' },
      middle: {
        root1: 'Rast',
        pow1: 'Rast',
        root2: 'Neva',
        pow2: 'Rast',
        root3: 'Neva',
        pow3: 'Buselik',
        root4: 'Neva',
        pow4: 'Uşşak',
      },
      end: { root1: 'Segah', pow1: 'Segah' },
    },
    desc: 'Makamı adını veren perde olan Segah üzerindeki Segah çeşnisi makamın başlangıç noktasını oluşturur. Ardından Rast üzerindeki Rast çeşnisine geçer. Daha sonra Neva perdesi ekseninde önce Rast, sonra Buselik ve en son Uşşak çeşnilerini gösterir. Segah üzerindeki segah çeşnisiyle başladığı şekliyle karar verir. Makamın olası geçki ve genişlemeleri için bkz. Çeşni Evreni.',
  },
]
